---
version: '3.7'
services:
  app:
    build: proj
    volumes:
      - /data:/tmp/App42/target/ 

  prod:      
    image: tomcat:9.0
    ports:
      - "8081:8080"
    volumes:
      - /data:/usr/local/tomcat/webapps/
    depends_on:
      - app
      - bd

  bd:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      # - MYSQL_DATABASE=bd
      # - MYSQL_USER= acp4pogynvaeidfj
      # - MYSQL_PASSWORD=jc31d2qyy7h9jv5jn1u9uosjksxzaizw
    ports:
      - "3306:8514"  
    volumes:
      # - ./mysql:/app42/App42/src/shephertz/app42/paas/sample
      - ./mysql:/var/lib/mysql
